image:
- Visual Studio 2017
environment:
  matrix:
  - BINARY: 64
  - BINARY: 32
install:
- cmd: set MSYS2_ARCH=x86_64
- cmd: if %BINARY%==32 set MSYS2_ARCH=i686
- cmd: set MSYSTEM=MINGW%BINARY%
- cmd: set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
- cmd: bash -xlc "pacman --noconfirm --sync --refresh pacman"
- cmd: bash -xlc "pacman --noconfirm --sync --refresh --sysupgrade"
- cmd: bash -xlc "pacman --noconfirm -S --needed base-devel"
- cmd: bash -xlc "pacman --noconfirm -S --needed mingw-w64-%MSYS2_ARCH%-toolchain"
- cmd: set CHERE_INVOKING=yes
build_script:
- cmd: bash -xlc "make LDFLAGS=-static DYNAMIC_ARCH=1 NUM_THREADS=128 NO_LAPACK=1 USE_THREAD=1 ONLY_CBLAS=1 BINARY=%BINARY%"
- cmd: bash -xlc "make PREFIX=./install/dist%BINARY% install"
after_build:
- cmd: 7z a openblas_%BINARY%.zip .\install\*
artifacts:
  - path: openblas_$(BINARY).zip
    name: openblas_$(BINARY)_zip
deploy:
  - provider: GitHub
    artifact: openblas_$(BINARY).zip
    auth_token:
      secure: cDBBHS9pbSEEe+Dt/kGjHCrSPqaTQuZsrvFETud2tfVwTTnm7JneWQLB1n6Z+L6/
    on:
      appveyor_repo_tag: true

