image:
- Visual Studio 2017
environment:
  matrix:
  - NAME: android-aarch64
  - NAME: android-armv7a
  - NAME: android-i686
  - NAME: android-x86_64
install:
- cmd: set PATH=C:\msys64\usr\bin;%PATH%
- cmd: set CHERE_INVOKING=yes
- cmd: set PATH=C:\Python36;C:\Python36\scripts;%PATH%
- cmd: IF %NAME%==android-aarch64 C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r17\build\tools\make_standalone_toolchain.py --arch arm64 --api 21 --stl libc++ --install-dir \android-standalone
- cmd: IF %NAME%==android-armv7a C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r17\build\tools\make_standalone_toolchain.py --arch arm --api 19 --stl libc++ --install-dir \android-standalone
- cmd: IF %NAME%==android-i686 C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r17\build\tools\make_standalone_toolchain.py --arch x86 --api 19 --stl libc++ --install-dir \android-standalone
- cmd: IF %NAME%==android-x86_64 C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r17\build\tools\make_standalone_toolchain.py --arch x86_64 --api 21 --stl libc++ --install-dir \android-standalone
- cmd: set PATH=C:\android-standalone\bin;%PATH%
build_script:
- cmd: IF %NAME%==android-armv7a bash -xlc "make TARGET=ARMV7 ARM_SOFTFP_ABI=1 HOSTCC=gcc CC=arm-linux-androideabi-gcc CFLAGS='-march=armv7-a -D__ANDROID_API__=21' NOFORTRAN=1 NO_SHARED=1"
- cmd: IF %NAME%==android-aarch64 bash -xlc "make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc CFLAGS=-D__ANDROID_API__=19 NOFORTRAN=1 NO_SHARED=1"
- cmd: IF %NAME%==android-i686 bash -xlc "make BINARY=32 HOSTCC=gcc CC=i686-linux-android-gcc CFLAGS=-D__ANDROID_API__=19 NOFORTRAN=1 NO_SHARED=1 DYNAMIC_ARCH=1 NUM_THREADS=128 NO_LAPACK=1 USE_THREAD=1 ONLY_CBLAS=1"
- cmd: IF %NAME%==android-x86_64 bash -xlc "make BINARY=64 HOSTCC=gcc CC=x86_64-linux-android-gcc CFLAGS=-D__ANDROID_API__=21 NOFORTRAN=1 NO_SHARED=1 DYNAMIC_ARCH=1 NUM_THREADS=128 NO_LAPACK=1 USE_THREAD=1 ONLY_CBLAS=1"
- cmd: bash -xlc "make PREFIX=./install/%NAME% NO_SHARED=1 install"
after_build:
- cmd: 7z a openblas-%NAME%.zip .\install\*
artifacts:
  - path: openblas-$(NAME).zip
    name: openblas-$(NAME)_zip
deploy:
  - provider: GitHub
    artifact: openblas-$(NAME).zip
    auth_token:
      secure: cDBBHS9pbSEEe+Dt/kGjHCrSPqaTQuZsrvFETud2tfVwTTnm7JneWQLB1n6Z+L6/
    on:
      appveyor_repo_tag: true
